const clinical_dummy_data = [
    {
        _id: 1,
        visit_date: '01-12-2023',
        a1c: '4.0',
        systolic_blood_pressure: '50',
        height: '130',
        weight: '50',
        bmi: '133',
        prescription: 'One sachet of panadol, two bottle of blood tonic,10 injections for your bom-bom',
    },
    {
        _id: 2,
        visit_date: '2-11-2023',
        a1c: '7.0',
        systolic_blood_pressure: '150',
        height: '200',
        weight: '90',
        bmi: '283',
        prescription: 'One sachet of panadol, two bottle of blood tonic,10 injections for your bom-bom',
    },
    {
        _id: 3,
        visit_date: '04-2-2023',
        a1c: '9.0',
        systolic_blood_pressure: '215',
        height: '190',
        weight: '90',
        bmi: '803',
        prescription: 'One sachet of panadol, two bottle of blood tonic,10 injections for your bom-bom',
    },
    {
        _id: 4,
        visit_date: '01-10-2024',
        a1c: '14.0',
        systolic_blood_pressure: '350',
        height: '100',
        weight: '120',
        bmi: '500',
        prescription: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Veritatis fugiat sequi dicta est, ipsam praesentium molestias culpa suscipit placeat! Deserunt illo ad repellat quo fugit?',
    },
]
export default clinical_dummy_data